export const SKILLS_SPECWORK_CONVENTIONS_SKILL = `# Specwork Conventions Skill

This skill defines the spec system built into Specwork. Specs, changes, and templates all live under \`.specwork/\` — no separate directory, no external dependency. Load this skill when creating/reviewing specs, working on change proposals, or understanding the proposal → spec → design → tasks → graph lifecycle.

---

## Overview

Specwork's spec system is a feature of Specwork itself — not a separate tool. Everything lives under \`.specwork/\`.

**Core insight**: specs are behavior contracts. They say WHAT the system must do, not HOW. Implementation details go in design.md; steps go in tasks.md; the "how" is Claude Code's job.

---

## Directory Layout

\`\`\`
.specwork/
├── config.yaml              # Unified config: engine settings + spec conventions
├── schema.yaml              # Artifact dependency graph (proposal → specs → design → tasks)
├── templates/               # Starter templates for each artifact type
│   ├── proposal.md
│   ├── spec.md
│   ├── design.md
│   └── tasks.md
├── specs/                   # Source of truth — current deployed behavior
│   └── <capability>/        # One folder per capability (kebab-case)
│       └── spec.md          # WHAT the system does (behavior contracts)
├── changes/                 # Proposed modifications (in-flight work)
│   ├── <change-name>/       # Descriptive kebab-case name
│   │   ├── .specwork.yaml    # Change metadata
│   │   ├── proposal.md      # WHY this change
│   │   ├── design.md        # HOW to implement (optional)
│   │   ├── tasks.md         # Implementation checklist
│   │   └── specs/           # DELTA specs — only what changes
│   │       └── <capability>/
│   │           └── spec.md
│   └── archive/             # Completed changes (immutable history)
│       └── YYYY-MM-DD-<name>/
├── graph/                   # Execution graphs (generated by specwork-graph)
│   └── <change>/
│       ├── graph.yaml
│       └── state.yaml
└── nodes/                   # Runtime artifacts per node
    └── <change>/
        └── <node-id>/
            ├── L0.md, L1.md, L2.md
            └── verify.md, output.txt
\`\`\`

**Key rule**: \`.specwork/specs/\` = current deployed reality. \`.specwork/changes/\` = proposed future state. Never mix them.

---

## Spec Format

Specs use structured markdown for machine parseability and human readability.

### Full Spec (in \`.specwork/specs/<capability>/spec.md\`):

\`\`\`markdown
# <Capability Name> Specification

## Purpose
<One-paragraph description of what this capability covers.>

## Requirements

### Requirement: <Name Under 50 Chars>
The system SHALL <describe the core behavior>.

#### Scenario: <Descriptive scenario name>
- **GIVEN** <initial state> (optional)
- **WHEN** <condition or trigger>
- **THEN** <expected outcome>
- **AND** <additional outcome> (optional)
\`\`\`

### Critical Formatting Rules

| Rule | Detail |
|------|--------|
| Requirement headers | Exactly \`### Requirement: Name\` (3 hashtags) |
| Scenario headers | Exactly \`#### Scenario: Name\` (4 hashtags — **CRITICAL**, never 3) |
| SHALL/MUST | Absolute requirement (RFC 2119) |
| SHOULD | Recommended, exceptions exist |
| MAY | Optional |
| GIVEN | Initial state setup — optional |
| WHEN | Trigger condition — required |
| THEN | Expected outcome — required |
| AND | Additional outcomes/conditions |
| No duplicates | No duplicate \`### Requirement:\` headers within a spec |
| Behavior only | No class/function names, no library choices |
| Testable | Each scenario should be a potential test case |

---

## Delta Spec Format

Delta specs live at \`.specwork/changes/<name>/specs/<capability>/spec.md\`. They describe **only what changes** relative to the current spec in \`.specwork/specs/<capability>/spec.md\`.

\`\`\`markdown
## ADDED Requirements

### Requirement: <New Capability>
The system SHALL <new behavior>.

#### Scenario: <Happy path>
- **WHEN** <trigger>
- **THEN** <outcome>

## MODIFIED Requirements

### Requirement: <Existing Requirement Name — exact match>
The system SHALL <updated behavior>. ← (was: <previous behavior>)

#### Scenario: <Updated scenario>
- **WHEN** <trigger>
- **THEN** <new outcome>

## REMOVED Requirements

### Requirement: <Requirement Being Removed>
**Reason**: <why it's being removed>
**Migration**: <how users should adapt>

## RENAMED Requirements
- FROM: \`### Requirement: Old Name\`
- TO: \`### Requirement: New Name\`
\`\`\`

### Archive Processing Order (applied at archive time)
1. **RENAMED** first — establishes new header names
2. **REMOVED** second — deletes by header match
3. **MODIFIED** third — replaces full requirement by header match
4. **ADDED** last — appends to spec

**MODIFIED must include COMPLETE requirement content** — not a partial diff. Copy the entire \`### Requirement:\` block and edit it.

---

## Proposal Format

\`.specwork/changes/<name>/proposal.md\` — captures WHY and WHAT at a high level.

\`\`\`markdown
## Why
<1-2 sentences: problem being solved, why now>

## What Changes
<Bullet list. Mark breaking changes with **BREAKING**.>

## Capabilities
### New Capabilities
- \`capability-name\`: <brief description>

### Modified Capabilities
- \`existing-name\`: <what requirement is changing>

## Impact
<Affected files, dirs, systems>
\`\`\`

**Key**: The Capabilities section contracts between proposal and specs. Every capability listed here needs a corresponding spec file.

---

## Design Format

\`.specwork/changes/<name>/design.md\` — optional, only for complex changes.

**Create design.md when:**
- Cross-cutting change (multiple services/modules)
- New external dependency or significant data model changes
- Security, performance, or migration complexity
- Ambiguity that benefits from technical decisions before coding

**Skip design.md for:** bug fixes, simple additions, routine refactors.

---

## Tasks Format

\`.specwork/changes/<name>/tasks.md\` — implementation checklist. Checkboxes are parsed by \`specwork-graph\` to generate graph nodes.

\`\`\`markdown
## 1. <Task Group Name>
- [ ] 1.1 <Task description>
- [ ] 1.2 <Task description>
\`\`\`

Every task MUST use \`- [ ]\` format. Non-checkbox lines are ignored.

---

## Change Metadata

\`.specwork/changes/<name>/.specwork.yaml\` — per-change metadata.

\`\`\`yaml
schema: spec-driven
created: 2026-03-26
dependsOn: []       # Other change names that must be archived first
provides: []        # Capability markers this change exports
requires: []        # Capability markers this change needs
\`\`\`

---

## How Specs Flow to Graphs

The full lifecycle:

\`\`\`
1. PROPOSE    → .specwork/changes/<name>/proposal.md
2. SPECIFY    → .specwork/changes/<name>/specs/<capability>/spec.md
3. DESIGN     → .specwork/changes/<name>/design.md  (optional)
4. PLAN       → .specwork/changes/<name>/tasks.md
5. GENERATE   → /project:specwork-graph <name>  →  .specwork/graph/<name>/graph.yaml
6. EXECUTE    → /project:specwork-run <name>    →  walks the graph
7. ARCHIVE    → .specwork/changes/archive/YYYY-MM-DD-<name>/  (delta specs merged to .specwork/specs/)
\`\`\`

The \`/project:specwork-graph\` command reads \`tasks.md\` + \`design.md\` + \`proposal.md\` and generates a \`graph.yaml\` with one node per implementation task.

---

## Naming Conventions

**Capabilities** (kebab-case, singular focus):
- Good: \`graph-execution\`, \`context-assembly\`, \`scope-enforcement\`
- Bad: \`feature-1\`, \`stuff\`, \`misc\`

**Changes** (descriptive kebab-case):
- Good: \`add-auth-middleware\`, \`optimize-snapshot\`, \`fix-node-retry-loop\`
- Bad: \`update\`, \`wip\`, \`changes-2\`

---

## Progressive Rigor

Not every change needs all artifacts:

| Change Type | Rigor | Artifacts |
|-------------|-------|-----------|
| Bug fix, refactor, docs | None | Skip entirely |
| Small/routine feature | Lite | proposal + specs + tasks |
| Complex/risky feature | Full | proposal + specs + design + tasks |
| Breaking/cross-team | Full+ | All artifacts + detailed design |
`;
