export const SKILLS_SPECWORK_CONTEXT_SKILL = `# Specwork Context Skill

This skill defines the L0/L1/L2 progressive context resolution system used by Specwork to give subagents exactly the right amount of context — no more, no less.

Use \`specwork context\` CLI commands to assemble and retrieve context. Never read L0/L1/L2 files directly.

---

## Philosophy

Subagents don't need the full conversation history. They need to know:
1. What has already been done (L0 — all nodes, ultra-compressed)
2. What their parents produced (L1 — direct deps, summarized)
3. The full details of a specific node on demand (L2 — EXPAND only)

This keeps token budgets small while preserving decision-making context.

---

## CLI Commands for Context

### Assemble full context for a subagent
\`\`\`bash
specwork context assemble <change> <node-id>
\`\`\`
Returns the complete prompt block: L0 (all nodes) + L1 (parents) + snapshot + inputs + task. This is the primary command — use it before spawning any LLM subagent.

### Get L0 headlines only
\`\`\`bash
specwork context l0 <change>
\`\`\`
Returns one-line status for all completed nodes. Useful for status checks.

### Expand L2 for a specific node
\`\`\`bash
specwork context expand <change> <current-node-id> <target-node-id>
\`\`\`
Returns re-assembled context with full L2 of the target node injected under \`<expanded-context>\`. Only called when a subagent outputs \`EXPAND(target-node-id)\`.

---

## Context Tiers

### L0 — Graph State Headlines
- **Scope**: ALL completed nodes
- **Size**: ~10 tokens per node (one line each)
- **Content**: Status + one key stat
- **Location**: \`.specwork/nodes/<change>/<node-id>/L0.md\`
- **Format**: \`- <node-id>: complete, <one key stat>\`

L0 examples:
\`\`\`
- snapshot: complete, 47 files indexed
- write-tests: complete, 23 tests written (all red)
- impl-types: complete, 2 interfaces exported
- impl-service: complete, 3 functions, 8/8 tests pass
\`\`\`

**Rule**: L0 MUST be under 15 tokens per node. No sentences. Only facts.

---

### L1 — Parent Node Summaries
- **Scope**: ONLY direct parent nodes (listed in \`node.deps\`)
- **Size**: ~100 tokens per parent
- **Content**: Files, exports, decisions, test results
- **Location**: \`.specwork/nodes/<change>/<node-id>/L1.md\`
- **Format**: Structured prose, no code blocks

L1 example:
\`\`\`
### impl-types
Files: src/types.ts
Exports: interface GraphNode { id: string, type: NodeType, deps: string[], scope: string[] },
         interface GraphState { nodes: Record<string, NodeStatus> }
Decision: Used discriminated union for NodeType to allow exhaustive switch statements.
Tests: 4/4 unit tests passing after impl.
\`\`\`

**Rule**: L1 MUST be under 100 tokens. No code blocks. Interfaces written inline.

---

### L2 — Full Node Artifacts
- **Scope**: On-demand, via EXPAND mechanism
- **Size**: Unlimited (~1000+ tokens typical)
- **Content**: Full git diff + verify.md + subagent output
- **Location**: \`.specwork/nodes/<change>/<node-id>/L2.md\`
- **Generated by**: \`specwork-summarizer\` (or \`node-complete.sh\` hook)

L2 is never loaded automatically. A subagent must explicitly request it via \`EXPAND(node-id)\`.

---

## Context Budget Calculations

When assembling context for a subagent, estimate token usage:

| Component | Tokens (approx) |
|-----------|-----------------|
| L0 per completed node | ~10 |
| L1 per parent node | ~100 |
| Environment snapshot | ~500-2000 |
| Input files | varies |
| Task description | ~100 |
| System prompt overhead | ~500 |

**Budget target**: Keep total context under 8,000 tokens for Haiku nodes, under 20,000 for Sonnet, under 50,000 for Opus.

\`specwork context assemble\` respects these budgets automatically. If L0 + L1 + snapshot exceeds budget, it prioritizes:
1. Snapshot (always include)
2. L1 parents (always include)
3. L0 (truncate to most recent N nodes if needed)

---

## EXPAND Mechanism

If a subagent needs full details from a previous node (e.g., the actual diff, the full test file), it signals this by outputting EXPAND as its FIRST line:

\`\`\`
EXPAND(impl-types)
[rest of output is discarded]
\`\`\`

The engine then:
\`\`\`bash
specwork context expand <change> <current-node-id> impl-types
\`\`\`

This:
1. Reads \`.specwork/nodes/<change>/impl-types/L2.md\`
2. Re-assembles context, adding:
   \`\`\`
   <expanded-context node="impl-types">
   [full L2 content]
   </expanded-context>
   \`\`\`
3. Returns the expanded prompt for re-spawning the subagent
4. This can only happen ONCE per node execution (\`expand_limit: 1\`)

**Use EXPAND sparingly** — it adds latency and cost. Only request it when L1 is genuinely insufficient to complete the task.

---

## Writing Good Summaries

### L0 — Written by specwork-summarizer
Format: \`- <node-id>: complete, <stat>\`
Stats to use:
- For test-writer: \`N tests written (all red)\`
- For implementers: \`N functions, N/N tests pass\`
- For snapshot: \`N files indexed\`
- For integration: \`N/N tests pass\` or \`FAILED: N failures\`

### L1 — Written by specwork-summarizer
Structure:
1. \`Files:\` — comma-separated list of created/modified paths
2. \`Exports:\` — inline type signatures (no code block)
3. \`Decision:\` — one sentence on any non-obvious architectural choice and why
4. \`Tests:\` — test result summary

### L2 — Written by node-complete.sh hook
Concatenate in order:
1. \`git diff HEAD~1\` — full diff of the node's commit
2. \`---\` separator
3. Contents of \`verify.md\`
4. \`---\` separator
5. Subagent's full output (captured from Agent tool result)

---

## Context in Practice

**At write-tests node**: subagent sees full snapshot + L0 of just \`snapshot\` node.
**At impl-types node**: subagent sees snapshot + L0 of \`snapshot, write-tests\` + L1 of \`write-tests\`.
**At impl-service node**: subagent sees snapshot + L0 of all prior nodes + L1 of \`impl-types, write-tests\`.
**If impl-service needs the actual test code**: it outputs \`EXPAND(write-tests)\`, the engine calls \`specwork context expand\`, gets L2 of write-tests, re-runs.
`;
